# -*- coding: utf-8 -*-
"""CS2_Mahogany_Usman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0FuW3XHqaaMpKv064qA9FgywzzxoyUk

# 💻 Computer Science 2 Python: Clean and Readable Code

**Topic:** Standards of Modular Coding Design  
**Focus:** Proper Comments, Documentation, and Code Readability

In this notebook, you will practice making a Python program easier for **people** to read, understand, and improve.

### Learning Targets
By the end of this activity, you should be able to:
- write useful comments;
- use clear variable names;
- use proper spacing and indentation;
- organize code into clear sections; and
- create a simple `README.md` for a project.

> **Remember:** Clean code is not only code that works. It should also be easy to read, understand, and improve.

# Distance between Two Points Calculator

## Description
This program calculates the distance between two points.

## How to Run
1. Open the program.
2. Run the program.
3. Enter the required values. (x1, x2, y1, y2)

## Input Needed
- x1 (The x-coordinate of the first point)
- x2 (The y-coordinate of the first point)
- y1 (The x-coordinate of the second point)
- y2 (The y-coordinate of the second point)

## Sample Output


## Author
Name: Aliyyah Fatima A. Usman
Section: 8-Mahogany

## Part 1 — What Makes Code Readable?

Read the two programs below.

**Question:** Which program is easier for you to understand? Why?

Look for:
- clear variable names
- proper spacing
- indentation
- useful comments
- logical organization
"""

import math
x1=float(input("x1:"))
y1=float(input("y1:"))
x2=float(input("x2:"))
y2=float(input("y2:"))
d=math.sqrt(math.pow(x2-x1,2)+math.pow(y2-y1,2))
print(d)

import math

# Ask the user to enter the coordinates of the first point
x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))

# Ask the user to enter the coordinates of the second point
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

# Compute the distance using the distance formula
distance = math.sqrt(math.pow(x2 - x1, 2) + math.pow(y2 - y1, 2))

# Display the result rounded to two decimal places
print(f"The distance between the two points is: {distance:.2f}")

"""### ✏️ Think About It

Answer in your own words:

1. What makes the second program easier to read?
2. Which variable name is clearer: `d` or `distance`? Why?
3. Why are comments useful?
4. Why should comments explain important logic instead of repeating every line?

## Part 2 — Practice Writing Useful Comments

A good comment explains the **purpose** of an important part of the code.

**Weak comment:**
```python
# input
x1 = float(input("Enter x1: "))
```

**Better comment:**
```python
# Ask the user to enter the x-coordinate of the first point
x1 = float(input("Enter x1: "))
```

### Your Turn

Improve the comments in the code below. Replace the weak comments with comments that explain the purpose of the code.
"""

import math

# input
x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))

# input
x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

# answer
distance = math.sqrt(math.pow(x2 - x1, 2) + math.pow(y2 - y1, 2))

# print
print(f"The distance between the two points is: {distance:.2f}")

"""## Part 3 — Improve Variable Names

Clear variable names tell the reader what information is stored.

| Less Clear | Clearer |
|---|---|
| `d` | `distance` |
| `a` | `first_number` |
| `b` | `second_number` |
| `x` | `x_coordinate` |

**Task:** Rewrite the program below using clearer variable names.

Try to keep the program's output and purpose the same.
"""

import math

a = float(input("Enter x1: "))
b = float(input("Enter y1: "))
c = float(input("Enter x2: "))
e = float(input("Enter y2: "))

d = math.sqrt(math.pow(c - a, 2) + math.pow(e - b, 2))

print(f"Distance: {d:.2f}")

"""## Part 4 — Clean Code Challenge ⭐

Now combine what you learned.

Improve the program below by:

- adding meaningful comments;
- changing unclear variable names;
- fixing spacing;
- keeping proper indentation;
- organizing related instructions together; and
- making the final output easy to understand.

**Do not change what the program is supposed to calculate.**
"""

# Write your improved version here.
# Your goal is to make the code easy for another student to understand.

import math

x1=float(input("x1:"))
y1=float(input("y1:"))
x2=float(input("x2:"))
y2=float(input("y2:"))
d=math.sqrt(math.pow(x2-x1,2)+math.pow(y2-y1,2))
print(d)

"""## Part 5 — Test Your Improved Program 🧪

Test your program using these values:

- `x1 = 2`
- `y1 = 3`
- `x2 = 7`
- `y2 = 8`

Your program should display the distance rounded to **two decimal places**.

### Test Checklist

- [ ] The program runs without an error.
- [ ] Variable names are clear.
- [ ] Comments explain important parts.
- [ ] Code is properly spaced.
- [ ] Code is properly indented.
- [ ] The output is easy to understand.
"""

# Run your improved program here using the test values.
# You may replace the input() statements with the test values if you prefer.

"""## Part 6 — Create Your README.md

A `README.md` explains the **whole project**, while comments explain important parts of the code.

Your README should include:

1. **Project Title**
2. **Description**
3. **How to Run**
4. **Input Needed**
5. **Sample Output**
6. **Author**

### Simple Template

```markdown
# Project Title

## Description
Explain what your program does.

## How to Run
1. Open the program.
2. Run the program.
3. Enter the required values.

## Input Needed
- List the values the user needs to enter.

## Sample Output
Show an example of the program's output.

## Author
Name:
Section:
```

**Task:** Create your own `README.md` using the template above.

## Part 7 — GitHub Web Submission 🚀

According to the activity guide, your repository should contain:

```text
distance-calculator/
├── distance_calculator.py
└── README.md
```

### Upload Checklist

1. Open your GitHub account.
2. Create or open your repository.
3. Upload your improved Python file.
4. Upload your `README.md`.
5. Write a short and specific commit message.
6. Check that both files are visible.
7. Copy your repository link.
8. Submit the link through your LMS or Google Classroom.

**Example commit message:**
`Improved distance calculator with comments and README.`

## Part 8 — Exit Ticket 🎫

Answer briefly.

**1. What makes a comment useful?**

Your answer: ______________________________


**2. Why is a README.md file important?**

Your answer: ______________________________


**3. Give one way to make code more readable.**

Your answer: ______________________________


**4. What commit message would you use for this project, and why?**

Your answer: ______________________________


### Final Reminder

**Clean code = code that works + code that people can understand.**
"""